image: node:alpine

cache:
  paths:
    - node_modules/
    - .yarn
before_script:
  - apt-get update -qq && apt-get install
stages:
  - testing

Test:
  stage: testing
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn test
