language: node_js
node_js:
  - "10"

dist: trusty
sudo: false
deploy:
  provider: releases
  api_key: "204aeb974e103725d34bb863e092d20676e4c556"
  file: build
  skip_cleanup: true
  target-branch: master
  on:
    branch: dev
