language: node_js
node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn

jobs:
  include:
    - stage: testing
      script:
        - yarn test
    - stage: deploy
      script:
        - yarn build

stages:
  - name: testing
    # require the type to be a PR
  - name: deploy
    # require the type to be push to master
    if: type = push AND branch = master
