language: node_js
node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn

jobs:
  include:
    - stage: testing
      script:
        - yarn test
    - stage: deploy
      script:
        - yarn build

stages:
  - name: testing
  - name: deploy
      provider: releases
        api_key:
          secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDSbEW9D+lZbXB8zvJOD8g5Jzy+MKsko37hfGXtHyliVbJzGveMsmiTuvcAGoQBSuFaoU1a7FF9a9WYXFhip0nGfHGIsmMu75Qpp6+ORY845mQ+ZI6/sK61rMk2j4pPwtwHO5WMdUbs8vgudKS7ByIdmFbQhtCOHNdXzaQJSKZduEPf2hhA082oA2JfIlVWqq42JCYzhn5wghBVU23+OvEVzG74a1V6OQXoaH4lgb8pNC3GxPGB5XtesKh6RLmbnjZ4wwsVONTdKtZcO0l/cpBftVqsTkYHx+8E2mqI9Pvbyei6hp0WZwIkN2mDBIngTcpxWug+6hCr09k1CEVe68rAbOQo2CZHcUP+fxo36zW8aDAPohIybvcOrupbpz1BPtDkVdBhxhpABM0zcDY09dH0rqsDY0zW0eck1Z3jyUfG/9KHkXKZpf93Qnvq+iAn06M0P8EJN7HKpYMSLsQX0B5ugiRQ5Wj8IfLPYGJapUavTFu/xiDIIvdFx3k8W5VOi4hhE2naHHMV2dvNNkQKewTM6a8qIDFk4IKAUrgrNbDSbuXGv1Hy7dU0mBD2WVDxp8GWjlyvFiB1I+XFwBIdXbyZtoD7LqsCWekDFbHwj+vP4y1ZWaDJ2JA8Iz44HSHIWXYbJPgCZVZYZByq9QgrHgeSL9Ksu08vud4o123b9NwfpQ== stasrazuvanov@gmail.com
        file: "build"
