language: node_js
node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn

script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
  - yarn test

after_success:
  - yarn build
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: build
  skip_cleanup: true
  target-branch: master
  on:
    branch: dev
