language: node_js
node_js:
  - "10"

dist: trusty
sudo: false
deploy:
  - provider: script
  user: "stasrazuvanov@gmail.com"
  password: "JamesCross07111970"
  file: build
  skip_cleanup: true
  target-branch: master
  on:
    branch: dev
